# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'TrendingMovies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrendingMovies
  pod 'Alamofire'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Moya/RxSwift'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'RealmSwift'
  pod 'ReachabilitySwift'

  target 'TrendingMoviesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrendingMoviesUITests' do
    # Pods for testing
  end

  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
          end
      end
  end
  
end
